#pragma once

// Forward declarations for all game classes to break circular dependencies

class MinecraftServer;
struct RustPacket;
class ByteBuffer;
class NetHandler;
class NetLoginHandler;
class NetServerHandler;
class NetworkManager;
class NetworkListenThread;
class ServerConfigurationManager;
class EntityTracker;
class EntityTrackerEntry;
class World;
class Chunk;
class Block;
class Item;
class ItemStack;
class Entity;
class EntityLiving;
class EntityAnimals;
class EntityMob;
class EntityZombie;
class EntitySkeleton;
class EntitySpider;
class EntityCreeper;
class EntityPig;
class EntitySheep;
class EntityCow;
class EntityChicken;
class EntityPlayer;
class EntityPlayerMP;
class EntityArrow;
class TileEntity;
class AxisAlignedBB;
class Vec3D;
struct MovingObjectPosition;
class Material;
class PropertyManager;
class ItemInWorldManager;
